sudo: false
services: mongodb
language: node_js
node_js:
- '6'
install:
- "./command.sh install"
script:
- "./command.sh build"
- "./command.sh test"
before_deploy: "./command.sh release"
deploy:
  provider: npm
  email: j.lopez.r@gmail.com
  api_key:
    secure: kpR+iSSchgpag6aHb/EHOqAQQ0jnhH1Yagu1FKhZbtbPSvAyZE5slBItwW7vs+b31qHzbIzneprId9YqOKbIN1EBeklPHBt46fFkjkuBySRNHvlDCbaREhVnnIfjU//eCadSy1t3Cyf/yM+j3hcPOl1kTTO8aLm5Q9XlOcv5UNPiy3BZdmyHaJshtIj0+ZhQXOUboAdeBvfCzgdRai5bxZowyioVnXegAAJm4yEz9gCCE4i2a7oRTDJf6DtR/S7z86PD/ZU/hXXQ6bxqDPqbGhUVJnmRx1zVFIBk16DSMUMBQy8KIDx/gxCrR5FaOncSagVI6aMJCJYwYq8ms3xKQL+1NNZQ0mYa4M6XX2eU/6U80L+B+zqu7KZcx2z06dIH34Vn0LQ/08KcbOf1C91CgiWEIXC/pZNY9VdEZXzjDlhYBvcvlo+Umu59dM+JE8tKqg0FAy9JBleI2XFHyYbQnjaz7lkKIrc2GILl4fyJMSbnLH+kBJwKb15Mw881AM0P+iCNJJ+LW4x6B8HP/T8cGxXamkfzEaQfCZLxkh/ZMZNOIDHn4Sf9umntCWrGEIQLG4nCeCpPSNJW2IZE2p4aQZsfhn4J3loGFuVEY8u4TQuhZ1ZTSZnNgb0q3S77/S2jXApTRLG2ChAoUI5fy2CBrmRtipF0rAm2qWpz6Yy00zQ=
  on:
    tags: true
    repo: RouteInjector/route-injector
addons:
  code_climate:
    repo_token: ccd09456360940e25548406da9b0427dd12cd1ab07c040ea302b3e344a158f8a
notifications:
  email:
    on_success: change
    on_failure: always
  slack:
    secure: md0LdTHXFkbgRytuYn389fR/NI+sbnvQHJj3CKWAlhtwpw2jD2YdxUFJQv/la3fxDOVyfbkmhltd1lsyakqO6ak/JC42NkLAzbno3f35FVAcpthroLOd4RAFzcN3vSWZwdzBcAayUOElEkvc4nafu5MkTJ5PaS3drazeV7CRuF/OBECW2UpADYFwOjzvm5zT5FO7Ymb4LCdJ5PdvDyNnCY/6pmS1jAX4YK7mlN6N6+dhuNAgsbKFSElmn11qLwklKge7yFC+KPxu28UZhkr53NBZTtOEf7tt9dm9vr2y2OeMJqckmFw5FlaBdP0PjfgOExyULF+jH6YdbKnruoKXNuDEG/rSutAnhZtpQG9e6OnJC7BtjlvJIo3AXKtrz/MyKR5yguQ5fqHrysYt2Lk7CYwWOJS38EY36UYJHFPduT9NoFhCkGSWKlWRgZdt89GoT2wzhXW2L5/lRpfsPaUayOwUkrc9eu0owhA2Z6wXp4wdlkQDHgoXZ93jY5JsuFyDOobtg2oBDQT/NSjAPNt/SLyY2B5cS0CuGzln5x/W0XJ8law4YUHcCVBqPC3m7SNABQdkMiNmevc5UJITWnfA2+3k3lRvZWG9yUGadiFNB+9bco3aDB4gBu4YyG5yipchJiitd5XjR/aV4hqugmAz6wDAbDkxz5+EttJf6SLfD18=
    template:
    - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
    - 'Change view : %{compare_url}'
    - 'Build details : %{build_url}'
